# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SaintsFall Portifolio
email: caio.f.santos@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Landing page for Saintsfall.
  Gathering all projects and plans of me, an enthusiast trying to change gears on my profissional carrer, a passioned writer (wannabe), musician (not even close) and Frontend Developer (not yet, but crossing that bridge).
  Here I will try to showcase all my passions and obssessions, let's see what happens...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Custom variables
github_path: https://github.com/saintsfall
linkedin_path: https://www.linkedin.com/in/caio-santos-46833266/

# Build settings
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer


exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
